language: c

env:
  global:
    - secure: "a0jFomi8ZiuGDAq/AQp0nwdSxvwrS8hXNeAQRhHZ/z8fn7Ez3XLioBDOmg3qTCLxbyjKOmsLUUx86l2SbZ8/flnftAy6mlV4BHte6SwaiNdYZZKIWBmnOZSsGWsuAjekKw9E3mFQ43DMMom7xIuuGw57KU32Rb3BbOIFJWQuBf7d49Q+R0AJKsB0VfT3vPZbYobXKpWhQfdzsAB8EhqWg0B6/6NqP9uo5T6q2lJMrkblpAMbvJOnQFa0e9NLJNVnMbbUAepukf/dnuzZNJz+iiFH/j9L1igwKsPK6CRl42NJlslmb6ib2xIoK8zmie+dMzD02mYDQpCKofV+STnm/IDX3zAuGxMJADUmuUJTUgH/aL/AsbBrpnHUpkQj+2sbkqTdKsyMzRnmuSbpsInHas6fzj9PUaBBrwdCfCNkCWrgOof+Xg3gtWNd9XWrYqe/T7lWbeQR3l0HbQXnWYj9yq62UEYW0KMjgeGBZxEMWvOSC9AS9g0BFFW7PPNXuxaxkN18JYc+3ytaqaSAkslgPL+i8nabSxxiEHss6LqR1ilsV3+rqOcnZggXLWXQuRaon8Q0WY2Hyuv7jfYRhfpKMJI8POUK4Uisow6XivnjImQbfEplM9/6qleVKTqQFAdJ7TtBDa3+Aloe/MqFfaPtbfjd1GBpZl1pnRrlV3opsxs="
    - PATH=/opt/mingw-w64-i686/bin:/opt/mingw-w64-x86_64/bin:${PATH}


before_install:
  - sudo dpkg --purge cmake cmake-doc cmake-data
  - curl http://download.opensuse.org/repositories/home:/doc_bacardi/xUbuntu_12.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/doc_bacardi/xUbuntu_12.04 ./" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get --assume-yes install mingw-w64-mbs
  - sudo apt-get --assume-yes install gcc-multilib g++-multilib make libudev-dev libreadline6-dev
  - sudo apt-get --assume-yes install cmake3
  - sudo apt-get --assume-yes install p7zip-full
  - sudo apt-get --assume-yes install python-pip python-virtualenv
  - wget https://github.com/muhkuh-sys/org.lua-lua/releases/download/v5.1.1/lua.zip
  - mkdir lua
  - 7z x -olua lua.zip
  - virtualenv ~/virtualenv/python2.7
  - source ~/virtualenv/python2.7/bin/activate
  - pip install -q requests


# This is the command to build the whole project and pack the results in a distributable form.
script:
  - ./.build.sh
  - python installer/ivy/deploy.py build/artifacts/artifacts_mhash.xml


deploy:
  provider: releases
  api_key:
    secure: mrw32k5aKAP2p/1RnkNGKa9Gc2Vu3bASqb3ryiCWNif22RLuCts2eMwTr2mPnc/umRVYyHqggPJf+BcPkvAgxgwo4paN7JwED35RMDSP+ghLEcPQyS7VEj5SrWqF9vYm9AZ6pw8aTqLvemgdcjMJa/jzJ/UtovLq79vJ+i+SqBw=
  file:
    - build/lua.zip
    - build/ivy.xml
  skip_cleanup: true
  on:
    repo: muhkuh-sys/org.muhkuh.lua-mhash
    tags: true
