language: c

env:
  global:
    - PATH=/usr/mingw-w64-i686/bin:/usr/mingw-w64-x86_64/bin:${PATH}


before_install:
  - sudo dpkg --purge cmake cmake-doc cmake-data
  - curl http://download.opensuse.org/repositories/home:/doc_bacardi/xUbuntu_12.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/doc_bacardi/xUbuntu_12.04 ./" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get --assume-yes install mingw-w64-mbs
  - sudo apt-get --assume-yes install gcc-multilib g++-multilib make libudev-dev libreadline6-dev
  - sudo apt-get --assume-yes install cmake3 swig3


# This is the command to build the whole project and pack the results in a distributable form.
script:
  - ./.build.sh
